version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Sao_Paulo'
    groups:
      minor-and-patch:
        update-types: ['minor', 'patch']
    open-pull-requests-limit: 5
    labels: ['dependencies', 'npm']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      actions:
        update-types: ['minor', 'patch']
    open-pull-requests-limit: 3
    labels: ['dependencies', 'github-actions']
